import Head from "next/head";
import AllCmuccdcSmall from "../components/AllCmuccdcSmall";
import AllYakkawSmall from "../components/AllYakkawSmall";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section>
          <AllYakkawSmall />
        </section>
        <section>
        <AllCmuccdcSmall/>
        </section>
      </main>
    </div>
  );
}
