import Head from "next/head";
import Link from "next/link";
import AllCmuccdcSmall from "../components/AllCmuccdcSmall";
import AllYakkawSmall from "../components/AllYakkawSmall";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section className="py-8 ">
          <div className="bg-gray-100">
            <h2 className="text-3xl">Yakkaw</h2>
            <p className="py-1">
              ข้อมูลเฉลี่ย 6 ชั่วโมงต่อเนื่อง แสดงตัวเลขค่าฝุ่น PM2.5 หน่วย{" "}
              <span>
                μg/m<sup>3</sup>
              </span>
            </p>
            <Link href={"/yakkaw"}>
              <a>ดูเพิ่มเติม</a>
            </Link>
          </div>

          <AllYakkawSmall />
        </section>
        <section className="py-8">
          <h2 className="text-3xl">CMU CCDC</h2>
          <p className="py-1">
            ข้อมูลรายชั่วโมง แสดงตัวเลขค่าฝุ่น PM2.5 หน่วย{" "}
            <span>
              μg/m<sup>3</sup>
            </span>
          </p>
          <AllCmuccdcSmall />
        </section>
      </main>
    </div>
  );
}
